version: '3.8'
services:
  licensemanagerdb:
    image: postgres:15
    container_name: licensemanager_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin123!
      - POSTGRES_DB=master
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d master"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"  # Expose the database
    networks:
      - app-network

  licensemanager:
    image: licensemanager-api:latest
    container_name: licensemanager_api
    build:
      context: .
      dockerfile: LicenseManager.API/Dockerfile
    ports:
      - "5666:5666"  
    environment:
      - ASPNETCORE_URLS=http://+:5666
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__WriteTo__0__Args__serverUrl=http://seq:5341  
      - DatabaseConfiguration__ConnectionString=Server=licensemanager_db;Port=5432;Database=master;User Id=admin;Password=Admin123!;
      - DB_HOST=licensemanager_db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_NAME=master
    depends_on:
      - seq
      - licensemanagerdb
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8095:8080"  # Expose Adminer GUI on port 8095
    networks:
      - app-network

  seq:
    image: datalust/seq:latest
    container_name: seq_server
    restart: always
    ports:
      - "5341:5341"  # Seq UI and ingestion port
      - "8091:80"    # Optional: Expose Seq's HTTP API
    environment:
      - ACCEPT_EULA=Y  # Accept Seq EULA
    volumes:
      - seq_data:/data  # Persistent data storage for logs
    networks:
      - app-network

volumes:
  seq_data:  # Shared storage for Seq

networks:
  app-network:
    driver: bridge